// statsData for pie chart section
export const statsData = [
  {
    title: "Blood Centres",
    total: 4450,
    pieData: [
      { name: "Govt", value: 1282 },
      { name: "Private", value: 1658 },
      { name: "Chartered", value: 1406 },
      { name: "Redcross", value: 104 },
    ],
    groups: [
      { label: "Govt", value: 1282 },
      { label: "Private", value: 1658 },
      { label: "Chartered", value: 1406 },
      { label: "Redcross", value: 104 },
    ],
  },
  {
    title: "Active Blood Centres",
    total: 3613,
    pieData: [
      { name: "Govt", value: 1019 },
      { name: "Private", value: 1299 },
      { name: "Chartered", value: 1205 },
      { name: "Redcross", value: 90 },
    ],
    groups: [
      { label: "Govt", value: 1019 },
      { label: "Private", value: 1299 },
      { label: "Chartered", value: 1205 },
      { label: "Redcross", value: 90 },
    ],
  },
  {
    title: "Licensed Blood Centres",
    total: 2829,
    pieData: [
      { name: "Govt", value: 702 },
      { name: "Private", value: 1025 },
      { name: "Chartered", value: 1039 },
      { name: "Redcross", value: 63 },
    ],
    groups: [
      { label: "Govt", value: 702 },
      { label: "Private", value: 1025 },
      { label: "Chartered", value: 1039 },
      { label: "Redcross", value: 63 },
    ],
  },
  {
    title: "BSU",
    total: 1459,
    pieData: [
      { name: "Govt", value: 1448 },
      { name: "Other", value: 11 },
    ],
    groups: [
      { label: "Govt", value: 1448 },
      { label: "Other", value: 11 },
    ],
  },
];

// today's stats bar chart section
export const todaysStatsData = [
  {
    title: "Today's Blood Availability",
    total: 2033736,
    barData: [
      { type: "AB- ve", count: 44904 },
      { type: "AB+ ve", count: 659585 },
      { type: "A- ve", count: 31676 },
      { type: "A+ ve", count: 431666 },
      { type: "B- ve", count: 41064 },
      { type: "B+ ve", count: 624169 },
      { type: "Oh- ve", count: 168 },
      { type: "Oh+ ve", count: 1250 },
      { type: "O- ve", count: 14266 },
      { type: "O+ ve", count: 184988 },
    ],
    labelKey: "type",
    dataKey: "count",
  },
  {
    title: "Today's Blood Component Availability",
    total: 973169,
    barData: [
      { type: "Whole Blood", count: 38544 },
      { type: "Packed Red Blood Cells", count: 233865 },
      { type: "Fresh Frozen Plasma", count: 644436 },
      { type: "Plasma", count: 12351 },
      { type: "Platelet Concentrate", count: 10076 },
      { type: "Cryoprecipitate", count: 21854 },
      { type: "Cryo Poor Plasma", count: 11691 },
      { type: "Single Donor Platelet", count: 352 },
    ],
    labelKey: "type",
    dataKey: "count",
  },
  {
    title: "Donor Registered",
    total: 3917986,
    barData: [
      { state: "Andaman and Nicobar Islands", count: 181 },
      { state: "Andhra Pradesh", count: 59380 },
      { state: "Arunachal Pradesh", count: 2489 },
      { state: "Assam", count: 4960 },
      { state: "Bihar", count: 431734 },
      { state: "Chandigarh", count: 819 },
      { state: "Chhattisgarh", count: 101702 },
      { state: "Nagar Haveli And Daman And Diu", count: 288 },
      { state: "Delhi", count: 326205 },
      { state: "Goa", count: 1114 },
      { state: "Gujarat", count: 53419 },
    ],
    labelKey: "state",
    dataKey: "count",
  },
];

// statewise stats bar charts (blood centres, active centres, licensed centres, BSU)
export const statewiseBars = [
  {
    title: "Blood Centres",
    barData: [
      { state: "Uttar Pradesh", value: 623 },
      { state: "Maharashtra", value: 419 },
      { state: "Tamil Nadu", value: 358 },
      { state: "Karnataka", value: 330 },
      { state: "Telangana", value: 297 },
      { state: "Rajasthan", value: 268 },
      { state: "Andhra Pradesh", value: 236 },
      { state: "Kerala", value: 207 },
      { state: "Gujarat", value: 206 },
      { state: "Punjab", value: 176 },
      { state: "Bihar", value: 117 },
      { state: "Madhya Pradesh", value: 106 },
      { state: "West Bengal", value: 96 },
      { state: "Odisha", value: 85 },
      { state: "Haryana", value: 75 },
      { state: "Jharkhand", value: 68 },
      { state: "Chhattisgarh", value: 54 },
      { state: "Uttarakhand", value: 53 },
      { state: "Assam", value: 41 },
      { state: "Goa", value: 17 },
      { state: "Himachal Pradesh", value: 14 },
      { state: "Tripura", value: 9 },
      { state: "Meghalaya", value: 7 },
      { state: "Manipur", value: 6 },
      { state: "Nagaland", value: 5 },
      { state: "Arunachal Pradesh", value: 4 },
      { state: "Mizoram", value: 4 },
      { state: "Sikkim", value: 3 },
    ],
    labelKey: "state",
    dataKey: "value",
  },
  {
    title: "Active Blood Centres",
    barData: [
      { state: "Uttar Pradesh", value: 534 },
      { state: "Maharashtra", value: 388 },
      { state: "Telangana", value: 270 },
      { state: "Rajasthan", value: 250 },
      { state: "Andhra Pradesh", value: 223 },
      { state: "Karnataka", value: 219 },
      { state: "Tamil Nadu", value: 218 },
      { state: "Gujarat", value: 196 },
      { state: "Punjab", value: 149 },
      { state: "Bihar", value: 100 },
      { state: "Madhya Pradesh", value: 96 },
      { state: "West Bengal", value: 90 },
      { state: "Kerala", value: 80 },
      { state: "Odisha", value: 74 },
      { state: "Haryana", value: 72 },
      { state: "Jharkhand", value: 70 },
      { state: "Chhattisgarh", value: 60 },
      { state: "Uttarakhand", value: 59 },
      { state: "Assam", value: 41 },
      { state: "Goa", value: 16 },
      { state: "Himachal Pradesh", value: 14 },
      { state: "Tripura", value: 9 },
      { state: "Meghalaya", value: 7 },
      { state: "Manipur", value: 6 },
      { state: "Nagaland", value: 5 },
      { state: "Arunachal Pradesh", value: 4 },
      { state: "Mizoram", value: 4 },
      { state: "Sikkim", value: 3 },
    ],
    labelKey: "state",
    dataKey: "value",
  },
  {
    title: "Licensed Blood Centres",
    barData: [
      { state: "Uttar Pradesh", value: 485 },
      { state: "Maharashtra", value: 284 },
      { state: "Telangana", value: 207 },
      { state: "Tamil Nadu", value: 198 },
      { state: "Rajasthan", value: 197 },
      { state: "Andhra Pradesh", value: 183 },
      { state: "Karnataka", value: 150 },
      { state: "Gujarat", value: 146 },
      { state: "Madhya Pradesh", value: 118 },
      { state: "Punjab", value: 100 },
      { state: "Bihar", value: 90 },
      { state: "West Bengal", value: 85 },
      { state: "Kerala", value: 80 },
      { state: "Odisha", value: 74 },
      { state: "Haryana", value: 72 },
      { state: "Jharkhand", value: 70 },
      { state: "Chhattisgarh", value: 60 },
      { state: "Uttarakhand", value: 59 },
      { state: "Assam", value: 41 },
      { state: "Goa", value: 16 },
      { state: "Himachal Pradesh", value: 14 },
      { state: "Tripura", value: 9 },
      { state: "Meghalaya", value: 7 },
      { state: "Manipur", value: 6 },
      { state: "Nagaland", value: 5 },
      { state: "Arunachal Pradesh", value: 4 },
      { state: "Mizoram", value: 4 },
      { state: "Sikkim", value: 3 },
    ],
    labelKey: "state",
    dataKey: "value",
  },
  {
    title: "BSU",
    barData: [
      { state: "Tamil Nadu", value: 280 },
      { state: "Karnataka", value: 156 },
      { state: "Maharashtra", value: 149 },
      { state: "Gujarat", value: 140 },
      { state: "Rajasthan", value: 117 },
      { state: "Madhya Pradesh", value: 96 },
      { state: "Andhra Pradesh", value: 86 },
      { state: "Bihar", value: 55 },
      { state: "West Bengal", value: 55 },
      { state: "Punjab", value: 50 },
      { state: "Kerala", value: 40 },
      { state: "Uttar Pradesh", value: 35 },
      { state: "Odisha", value: 32 },
      { state: "Jharkhand", value: 25 },
      { state: "Haryana", value: 21 },
      { state: "Assam", value: 18 },
      { state: "Chhattisgarh", value: 15 },
      { state: "Uttarakhand", value: 12 },
      { state: "Tripura", value: 10 },
      { state: "Goa", value: 8 },
      { state: "Manipur", value: 6 },
      { state: "Meghalaya", value: 5 },
      { state: "Nagaland", value: 4 },
      { state: "Arunachal Pradesh", value: 3 },
      { state: "Mizoram", value: 2 },
      { state: "Sikkim", value: 1 },
    ],
    labelKey: "state",
    dataKey: "value",
  },
];

// statewise table data
export const statewiseTableData = [
  { state: "Andhra Pradesh", bloodCentres: 236, activeBloodCentres: 223, licensedBloodCentres: 183, bsu: 86 },
  { state: "Arunachal Pradesh", bloodCentres: 4, activeBloodCentres: 4, licensedBloodCentres: 4, bsu: 3 },
  { state: "Assam", bloodCentres: 41, activeBloodCentres: 41, licensedBloodCentres: 41, bsu: 18 },
  { state: "Bihar", bloodCentres: 117, activeBloodCentres: 100, licensedBloodCentres: 90, bsu: 55 },
  { state: "Chhattisgarh", bloodCentres: 54, activeBloodCentres: 54, licensedBloodCentres: 54, bsu: 15 },
  { state: "Goa", bloodCentres: 17, activeBloodCentres: 16, licensedBloodCentres: 16, bsu: 8 },
  { state: "Gujarat", bloodCentres: 206, activeBloodCentres: 196, licensedBloodCentres: 146, bsu: 140 },
  { state: "Haryana", bloodCentres: 75, activeBloodCentres: 72, licensedBloodCentres: 72, bsu: 21 },
  { state: "Himachal Pradesh", bloodCentres: 14, activeBloodCentres: 14, licensedBloodCentres: 14, bsu: 14 },
  { state: "Jharkhand", bloodCentres: 68, activeBloodCentres: 70, licensedBloodCentres: 70, bsu: 25 },
  { state: "Karnataka", bloodCentres: 330, activeBloodCentres: 219, licensedBloodCentres: 150, bsu: 156 },
  { state: "Kerala", bloodCentres: 207, activeBloodCentres: 80, licensedBloodCentres: 80, bsu: 40 },
  { state: "Madhya Pradesh", bloodCentres: 106, activeBloodCentres: 96, licensedBloodCentres: 118, bsu: 96 },
  { state: "Maharashtra", bloodCentres: 419, activeBloodCentres: 388, licensedBloodCentres: 284, bsu: 149 },
  { state: "Manipur", bloodCentres: 6, activeBloodCentres: 6, licensedBloodCentres: 6, bsu: 6 },
  { state: "Meghalaya", bloodCentres: 7, activeBloodCentres: 7, licensedBloodCentres: 7, bsu: 5 },
  { state: "Mizoram", bloodCentres: 4, activeBloodCentres: 4, licensedBloodCentres: 4, bsu: 2 },
  { state: "Nagaland", bloodCentres: 5, activeBloodCentres: 5, licensedBloodCentres: 5, bsu: 4 },
  { state: "Odisha", bloodCentres: 85, activeBloodCentres: 74, licensedBloodCentres: 74, bsu: 32 },
  { state: "Punjab", bloodCentres: 176, activeBloodCentres: 149, licensedBloodCentres: 150, bsu: 50 },
  { state: "Rajasthan", bloodCentres: 268, activeBloodCentres: 250, licensedBloodCentres: 197, bsu: 117 },
  { state: "Sikkim", bloodCentres: 3, activeBloodCentres: 3, licensedBloodCentres: 3, bsu: 1 },
  { state: "Tamil Nadu", bloodCentres: 358, activeBloodCentres: 218, licensedBloodCentres: 198, bsu: 280 },
  { state: "Telangana", bloodCentres: 297, activeBloodCentres: 270, licensedBloodCentres: 207, bsu: 35 },
  { state: "Tripura", bloodCentres: 9, activeBloodCentres: 9, licensedBloodCentres: 9, bsu: 10 },
  { state: "Uttar Pradesh", bloodCentres: 623, activeBloodCentres: 534, licensedBloodCentres: 485, bsu: 35 },
  { state: "Uttarakhand", bloodCentres: 53, activeBloodCentres: 59, licensedBloodCentres: 59, bsu: 12 },
  { state: "West Bengal", bloodCentres: 96, activeBloodCentres: 90, licensedBloodCentres: 85, bsu: 55 },
];
